<div class="teacher">
    <p style="font-size: 15px">You have access to all out teacher's content in the website feel free to contact support if needed
        Some useful links you may need:<br><br><br>
        <a style="font-size: large" href="postQuiz.php">Make a new quiz</a>
        <br><a style="font-size: large" href="Leaderboard.php">Check Score of students</a>
        <br><a style="font-size: large" href="../../editQuiz.php">Edit / Delete Quiz</a>
    </p>
    <p>
        <p style="font-size: large; margin-top: 2%">
            <b>

            </b>
        </p>
    <br>
        <p style="font-size: 18px;">
            A user with teacher module access can add a quiz & questions into it.
            <br>
            Edit or Delete, Quiz or Any Desired question that is available. Also can set Score to whole quiz (*Marks will be equally divided by number of question) <br>& Also set <b>*Timeout*</b> of each question.
            <br>
            Default timeout of each questions if 30 Seconds (if timeout occurs question will automatically skip)
        </p>
    </p>
</div>