<div class="students">
    <p style="font-size: 22px">Being a student give you certain features available for your assessment which are being shown below:<br><br>
    <a href="takeQuiz.php">Take Quiz</a><br><a href="Leaderboard.php">Check Scores</a></p>
    <br><br>
    <p style="font-size: large; margin-top: 2%"><b>User can see correct option and option number under the Correct Answers tab (Click on answer option!)<br>In Remarks answer is shown in Correct, Wrong and Skipped.</b></p>
    <p style="font-size: 15px;">
    Registered user get this access by default. Students can take Quiz and check their answers & marks at the end of quiz.
    <br>
    After quiz user can save the scores (which will be shown on Leaderboard) or skip saving and try again later.
    <br>
    Note : <b>Last saved answers is shown on leaderboard.</b>
    </p>
</div>